version: "3.8"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-net

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "8010:5540"
    depends_on:
      - redis
    networks:
      - app-net

  alb:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"  # Optional, for redirect
    volumes:
      - ./alb/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./alb/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
    networks:
      - app-net

  frontend:
    build: ./frontend-app
    depends_on:
      - api-gateway
    networks:
      - app-net

  api-gateway:
    build: ./api-gateway
    ports:
      - "8081:8081"
    depends_on:
      - backend
      - lambda-producer
    networks:
      - app-net

  backend:
    build: ./backend-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-net

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-net

  lambda-producer:
    build: ./lambda-producer
    ports:
      - "3010:8081"
    depends_on:
      - rabbitmq
    networks:
      - app-net

  lambda-consumer:
    build: ./lambda-consumer
    depends_on:
      rabbitmq:
        condition: service_healthy
      backend:
        condition: service_started
    networks:
      - app-net  

volumes:
  pgdata:

networks:
  app-net: