services:
  alb:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"  # Optional, for redirect
    volumes:
      - ./alb/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./alb/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
    networks:
      - app-net

  frontend:
    build: ./frontend-app
    ports:
      - "8080:80"
    depends_on:
      - api-gateway
    networks:
      - app-net

  api-gateway:
    build: ./api-gateway
    ports:
      - "8081:8081"
    depends_on:
      - backend
      - lambda-producer
    networks:
      - app-net

  backend:
    build: ./backend-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-net

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"       # AMQP (for apps)
      - "15672:15672"     # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    networks:
      - app-net

  lambda-producer:
    build: ./lambda-producer
    ports:
      - "3001:8081"
    depends_on:
      - rabbitmq
    networks:
      - app-net

  lambda-consumer:
    build: ./lambda-consumer
    depends_on:
      - rabbitmq
      - backend
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net:
