global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3000']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8081']

  - job_name: 'lambda-producer'
    static_configs:
      - targets: ['lambda-producer:8081']

  - job_name: 'lambda-consumer'
    static_configs:
      - targets: ['lambda-consumer:8080']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
